export const AuthActionTypes = {
  CREATE_USER_START: " CREATE_USER_START",
  CREATE_USER_SUCCESS: " CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: " CREATE_USER_FAIL",

  LOGIN_USER_START: " LOGIN_USER_START",
  LOGIN_USER_SUCCESS: " LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: " LOGIN_USER_FAIL",

  GET_USER_START: " GET_USER_START",
  GET_USER_SUCCESS: " GET_USER_SUCCESS",
  GET_USER_FAIL: " GET_USER_FAIL",

  ADD_TO_CART_LOCALLY: " ADD_TO_CART_LOCALLY",
  REMOVE_FROM_CART_LOCALLY: " REMOVE_FROM_CART_LOCALLY",

  ADD_TO_CART_START: " ADD_TO_CART_START",
  ADD_TO_CART_SUCCESS: " ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAIL: " ADD_TO_CART_FAIL",

  GET_CART_START: " GET_CART_START",
  GET_CART_SUCCESS: " GET_CART_SUCCESS",
  GET_CART_FAIL: " GET_CART_FAIL",

  REMOVE_FROM_CART_START: " REMOVE_FROM_CART_START",
  REMOVE_FROM_CART_SUCCESS: " REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_FAIL: " REMOVE_FROM_CART_FAIL",

  ADD_ORDER_START: " ADD_ORDER_START",
  ADD_ORDER_SUCCESS: " ADD_ORDER_SUCCESS",
  ADD_ORDER_FAIL: " ADD_ORDER_FAIL",
};
export const ProductActionTypes = {
  CREATE_PRODUCT_START: " CREATE_PRODUCT_START",
  CREATE_PRODUCT_SUCCESS: " CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: " CREATE_PRODUCT_FAIL",

  GET_PRODUCTS_START: " GET_PRODUCTS_START",
  GET_PRODUCTS_SUCCESS: " GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: " GET_PRODUCTS_FAIL",

  GET_PRODUCTS_BY_CATEGORY_START: " GET_PRODUCTS_BY_CATEGORY_START",
  GET_PRODUCTS_BY_CATEGORY_SUCCESS: " GET_PRODUCTS_BY_CATEGORY_SUCCESS",
  GET_PRODUCTS_BY_CATEGORY_FAIL: " GET_PRODUCTS_BY_CATEGORY_FAIL",
};
